version: '3.3'
services:
    db:
      image: 'postgres'
      environment:
        - POSTGRES_PASSWORD=example
      volumes:
        - ./postgres_db:/var/lib/postgresql/data
      ports:
        - '5432:5432'